***1_Importing libraries and main things that are needed***

In [ ]:
import pandas as pd 
import sklearn
from sklearn.preprocessing import OneHotEncoder
from sklearn.mpdel_selection import train_test_split

In [10]:
data = {
    "Student_ID": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
                   11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
                   21, 22, 23, 24, 25, 26, 27, 28, 29, 30],

    "Name": ["Ali", "Ahmed", "Sara", "Ayesha", "Hamza", "Fatima", "Usman", "Maria", "Bilal", "Hina",
             "Saad", "Zainab", "Omer", "Iqra", "Danish", "Mehwish", "Asad", "Laiba", "Shahzaib", "Areeba",
             "Arslan", "Maham", "Faizan", "Anum", "Rehan", "Komal", "Shayan", "Sana", "Adnan", "Momina"],

    "City": ["Peshawar", "Islamabad", "Lahore", "Peshawar", "Quetta", "Karachi", "Lahore", "Islamabad", "Peshawar", "Karachi",
             "Quetta", "Lahore", "Islamabad", "Peshawar", "Karachi", "Quetta", "Lahore", "Islamabad", "Peshawar", "Karachi",
             "Quetta", "Lahore", "Islamabad", "Peshawar", "Karachi", "Quetta", "Lahore", "Islamabad", "Peshawar", "Karachi"],

    "Department": ["AI", "CS", "SE", "AI", "CS", "IT", "AI", "SE", "CS", "AI",
                    "IT", "CS", "AI", "SE", "IT", "AI", "CS", "IT", "AI", "SE",
                    "CS", "AI", "IT", "CS", "AI", "SE", "IT", "CS", "AI", "SE"],

    "Gender": ["Male", "Male", "Female", "Female", "Male", "Female", "Male", "Female", "Male", "Female",
               "Male", "Female", "Male", "Female", "Male", "Female", "Male", "Female", "Male", "Female",
               "Male", "Female", "Male", "Female", "Male", "Female", "Male", "Female", "Male", "Female"],

  "Transport": ["Bus", "Car", "Bus", "Bike", "Bus", "Car", "Bike", "Bus", "Car", "Bike",
              "Bus", "Car", "Bike", "Bus", "Car", "Bike", "Bus", "Car", "Bike", "Bus",
              "Car", "Bike", "Bus", "Car", "Bike", "Bus", "Car", "Bike", "Bus", "Car"],

   "Age": [21, 22, 20, 21, 23, 22, 20, 21, 23, 20,
        22, 21, 22, 20, 23, 21, 22, 20, 23, 21,
        22, 20, 21, 22, 23, 21, 20, 22, 23, 21],

   "Marks": [78, 85, 91, 88, 72, 95, 81, 89, 76, 93,
          68, 87, 90, 84, 79, 92, 74, 96, 82, 90,
          71, 94, 77, 86, 80, 88, 73, 97, 75, 91]
}

In [14]:
df=pd.DataFrame(data)
df.head()

   Student_ID    Name       City Department  Gender Transport  Age  Marks
0           1     Ali   Peshawar         AI    Male       Bus   21     78
1           2   Ahmed  Islamabad         CS    Male       Car   22     85
2           3    Sara     Lahore         SE  Female       Bus   20     91
3           4  Ayesha   Peshawar         AI  Female      Bike   21     88
4           5   Hamza     Quetta         CS    Male       Bus   23     72

***2_Selecting  x and y columns also storing the catogrical columns in a variable***

In [16]:
x=df.drop("Marks",axis=1)
y=df["Marks"]

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Student_ID  30 non-null     int64
 1   Name        30 non-null     str
 2   City        30 non-null     str
 3   Department  30 non-null     str
 4   Gender      30 non-null     str
 5   Transport   30 non-null     str
 6   Age         30 non-null     int64
 7   Marks       30 non-null     int64
dtypes: int64(3), str(5)
memory usage: 2.7 KB

In [23]:
categric=["City","Department","Gender","Transport"]

***3_Perfroming encoding now***

In [24]:
encoded_data=pd.get_dummies(categric)

In [25]:
encoded_data.head(10)

    City  Department  Gender  Transport
0   True       False   False      False
1  False        True   False      False
2  False       False    True      False
3  False       False   False       True