**1_Importing Pandas first**

In [5]:
import pandas as pd

**2_Downloading and importing sql.connector**

In [6]:
pip install mysql.connector

Requirement already satisfied: mysql.connector in D:\anaconda3\Lib\site-packages (2.2.9)
Note: you may need to restart the kernel to use updated packages.

In [8]:
import mysql.connector

In [10]:
conn=mysql.connector.connect(host='localhost',user='root',password='',database='world')

**3_Calling a specific table and also using SQL query**

In [15]:
pd.read_sql_query('SELECT * FROM city',conn)

C:\Users\khali\AppData\Local\Temp\ipykernel_15696\3404837950.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query('SELECT * FROM city',conn)

        ID            Name CountryCode       District  Population
0        1           Kabul         AFG          Kabol     1780000
1        2        Qandahar         AFG       Qandahar      237500
2        3           Herat         AFG          Herat      186800
3        4  Mazar-e-Sharif         AFG          Balkh      127800
4        5       Amsterdam         NLD  Noord-Holland      731200
...    ...             ...         ...            ...         ...
4074  4075      Khan Yunis         PSE     Khan Yunis      123175
4075  4076          Hebron         PSE         Hebron      119401
4076  4077        Jabaliya         PSE     North Gaza      113901
4077  4078          Nablus         PSE         Nablus      100231
4078  4079           Rafah         PSE          Rafah       92020

[4079 rows x 5 columns]

In [17]:
pd.read_sql_query("select * from city where CountryCode='AFG'",conn)

C:\Users\khali\AppData\Local\Temp\ipykernel_15696\2640712628.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("select * from city where CountryCode='AFG'",conn)

   ID            Name CountryCode  District  Population
0   1           Kabul         AFG     Kabol     1780000
1   2        Qandahar         AFG  Qandahar      237500
2   3           Herat         AFG     Herat      186800
3   4  Mazar-e-Sharif         AFG     Balkh      127800